WITH condition_values AS (
  SELECT *
  FROM UNNEST([
    STRUCT('Amazon House' AS card_name, 3 AS conditions),
    STRUCT('Science Museum' AS card_name, 4 AS conditions),
    STRUCT('Aquarium' AS card_name, 1 AS conditions),
    STRUCT('Gorilla Field Research' AS card_name, 3 AS conditions),
    STRUCT('Asian Elephant' AS card_name, 1 AS conditions),
    STRUCT('Medical Breakthrough' AS card_name, 4 AS conditions),
    STRUCT('Science Library' AS card_name, 0 AS conditions),
    STRUCT('Giant Panda' AS card_name, 3 AS conditions),
    STRUCT('African Bush Elephant' AS card_name, 1 AS conditions),
    STRUCT('Field Research Type D Orcas' AS card_name, 3 AS conditions),
    STRUCT('Diversity Researcher' AS card_name, 1 AS conditions),
    STRUCT('King Vulture' AS card_name, 3 AS conditions),
    STRUCT('Grevy\'s Zebra' AS card_name, 3 AS conditions),
    STRUCT('Reconstruction' AS card_name, 0 AS conditions),
    STRUCT('Federal Grants' AS card_name, 0 AS conditions),
    STRUCT('Polar Bear Exhibit' AS card_name, 0 AS conditions),
    STRUCT('Side Entrance' AS card_name, 0 AS conditions),
    STRUCT('Geologist' AS card_name, 0 AS conditions),
    STRUCT('Cable Car' AS card_name, 0 AS conditions),
    STRUCT('Pygmy Hippopotamus' AS card_name, 1 AS conditions),
    STRUCT('Bald Eagle' AS card_name, 1 AS conditions),
    STRUCT('Eurasian Brown Bear' AS card_name, 2 AS conditions),
    STRUCT('Red Panda' AS card_name, 2 AS conditions),
    STRUCT('Meerkat Den' AS card_name, 1 AS conditions),
    STRUCT('Snowy Owl' AS card_name, 2 AS conditions),
    STRUCT('Excavation Site' AS card_name, 0 AS conditions),
    STRUCT('Coastal Manta Ray' AS card_name, 1 AS conditions),
    STRUCT('Explorer' AS card_name, 1 AS conditions),
    STRUCT('Hydrologist' AS card_name, 0 AS conditions),
    STRUCT('Sun Bear' AS card_name, 1 AS conditions),
    STRUCT('Sumatran Tiger' AS card_name, 2 AS conditions),
    STRUCT('Spokesperson' AS card_name, 1 AS conditions),
    STRUCT('Mandrill' AS card_name, 3 AS conditions),
    STRUCT('Siberian Tiger' AS card_name, 3 AS conditions),
    STRUCT('Talented Communicator' AS card_name, 1 AS conditions),
    STRUCT('Andean Condor' AS card_name, 1 AS conditions),
    STRUCT('Cotton-top Tamarin' AS card_name, 2 AS conditions),
    STRUCT('Penguin Pool' AS card_name, 1 AS conditions),
    STRUCT('Golden Eagle' AS card_name, 1 AS conditions),
    STRUCT('Caribbean Reef Shark' AS card_name, 0 AS conditions),
    STRUCT('Engineer' AS card_name, 0 AS conditions),
    STRUCT('Science Lab' AS card_name, 1 AS conditions),
    STRUCT('Archaeologist' AS card_name, 1 AS conditions),
    STRUCT('Baboon Rock' AS card_name, 0 AS conditions),
    STRUCT('Underwater Tunnel' AS card_name, 1 AS conditions),
    STRUCT('Expert On Asia' AS card_name, 0 AS conditions),
    STRUCT('Long-billed Vulture' AS card_name, 1 AS conditions),
    STRUCT('Orange Clownfish' AS card_name, 0 AS conditions),
    STRUCT('African Penguin' AS card_name, 1 AS conditions),
    STRUCT('Tasmanian Devil' AS card_name, 1 AS conditions),
    STRUCT('Blackbar Triggerfish' AS card_name, 1 AS conditions),
    STRUCT('Nile Crocodile' AS card_name, 3 AS conditions),
    STRUCT('Zoo School' AS card_name, 0 AS conditions),
    STRUCT('Shoebill' AS card_name, 2 AS conditions),
    STRUCT('Moose' AS card_name, 2 AS conditions),
    STRUCT('Devil Firefish' AS card_name, 1 AS conditions),
    STRUCT('Landscape Gardener' AS card_name, 0 AS conditions),
    STRUCT('Guided School Tours' AS card_name, 0 AS conditions),
    STRUCT('Galapagos Giant Tortoise' AS card_name, 3 AS conditions),
    STRUCT('Guineafowl Puffer' AS card_name, 0 AS conditions),
    STRUCT('Expert On The Americas' AS card_name, 0 AS conditions),
    STRUCT('Northern Muriqui' AS card_name, 1 AS conditions),
    STRUCT('Technology Institute' AS card_name, 0 AS conditions),
    STRUCT('American Bison' AS card_name, 3 AS conditions),
    STRUCT('Foreign Institute' AS card_name, 0 AS conditions),
    STRUCT('Blackside Hawkfish' AS card_name, 0 AS conditions),
    STRUCT('Senegal Bushbaby' AS card_name, 2 AS conditions),
    STRUCT('Veterinarian' AS card_name, 0 AS conditions),
    STRUCT('Golden Snub-nosed Monkey' AS card_name, 1 AS conditions),
    STRUCT('Horse' AS card_name, 0 AS conditions),
    STRUCT('Dugong' AS card_name, 1 AS conditions),
    STRUCT('Longcomb Sawfish' AS card_name, 1 AS conditions),
    STRUCT('Australian Pelican' AS card_name, 0 AS conditions),
    STRUCT('Southern Blue-ringed Octopus' AS card_name, 0 AS conditions),
    STRUCT('Koala' AS card_name, 1 AS conditions),
    STRUCT('Horsfield\'s Tarsier' AS card_name, 1 AS conditions),
    STRUCT('Proboscis Monkey' AS card_name, 3 AS conditions),
    STRUCT('Lion' AS card_name, 3 AS conditions),
    STRUCT('Expert On Africa' AS card_name, 0 AS conditions),
    STRUCT('Red-shanked Douc' AS card_name, 1 AS conditions),
    STRUCT('Indian Cobra' AS card_name, 3 AS conditions),
    STRUCT('Barbary Macaque' AS card_name, 1 AS conditions),
    STRUCT('Lesser Flamingo' AS card_name, 0 AS conditions),
    STRUCT('Indian Peafowl' AS card_name, 1 AS conditions),
    STRUCT('Scarlet Macaw' AS card_name, 1 AS conditions),
    STRUCT('Bennett\'s Wallaby' AS card_name, 0 AS conditions),
    STRUCT('Quarantine Lab' AS card_name, 0 AS conditions),
    STRUCT('Brown Spider Monkey' AS card_name, 1 AS conditions),
    STRUCT('Arcade' AS card_name, 0 AS conditions),
    STRUCT('Red Kangaroo' AS card_name, 0 AS conditions),
    STRUCT('Mountain Tapir' AS card_name, 0 AS conditions),
    STRUCT('Australian Sea Lion' AS card_name, 1 AS conditions),
    STRUCT('Sponsorship: Primates' AS card_name, 1 AS conditions),
    STRUCT('Boa Constrictor' AS card_name, 2 AS conditions),
    STRUCT('Water Playground' AS card_name, 0 AS conditions),
    STRUCT('South American Coati' AS card_name, 0 AS conditions),
    STRUCT('Humphead Wrasse' AS card_name, 1 AS conditions),
    STRUCT('Donkey' AS card_name, 0 AS conditions),
    STRUCT('Mangalica' AS card_name, 0 AS conditions),
    STRUCT('Palette Surgeonfish' AS card_name, 0 AS conditions),
    STRUCT('Secretary Bird' AS card_name, 0 AS conditions),
    STRUCT('Panamanian White-faced Capuchin' AS card_name, 1 AS conditions),
    STRUCT('Basic Research' AS card_name, 1 AS conditions),
    STRUCT('Adventure Playground' AS card_name, 0 AS conditions),
    STRUCT('Waza Large Animal Program' AS card_name, 1 AS conditions),
    STRUCT('Brahminy Kite' AS card_name, 0 AS conditions),
    STRUCT('Expansion Area' AS card_name, 1 AS conditions),
    STRUCT('Victory Column' AS card_name, 0 AS conditions),
    STRUCT('Anaconda' AS card_name, 1 AS conditions),
    STRUCT('Compass Jellyfish' AS card_name, 1 AS conditions),
    STRUCT('Komodo Dragon' AS card_name, 2 AS conditions),
    STRUCT('Publications' AS card_name, 1 AS conditions),
    STRUCT('Longhorn Cowfish' AS card_name, 0 AS conditions),
    STRUCT('Native Farm Animals' AS card_name, 1 AS conditions),
    STRUCT('Magnificent Sea Anemone' AS card_name, 0 AS conditions),
    STRUCT('Leopard' AS card_name, 1 AS conditions),
    STRUCT('Grizzly Bear' AS card_name, 3 AS conditions),
    STRUCT('Domestic Rabbit' AS card_name, 0 AS conditions),
    STRUCT('Indian Rhinoceros' AS card_name, 1 AS conditions),
    STRUCT('Raccoon' AS card_name, 0 AS conditions),
    STRUCT('Bluespotted Ribbontail Ray' AS card_name, 0 AS conditions),
    STRUCT('New Zealand Fur Seal' AS card_name, 1 AS conditions),
    STRUCT('White Rhinoceros' AS card_name, 1 AS conditions),
    STRUCT('Alpine Ibex' AS card_name, 0 AS conditions),
    STRUCT('Lesser Bird-of-paradise' AS card_name, 0 AS conditions),
    STRUCT('Vietnamese Pot-bellied Pig' AS card_name, 0 AS conditions),
    STRUCT('Ornithologist' AS card_name, 0 AS conditions),
    STRUCT('Loggerhead Sea Turtle' AS card_name, 0 AS conditions),
    STRUCT('Northern Plains Gray Langur' AS card_name, 0 AS conditions),
    STRUCT('Science Institute' AS card_name, 0 AS conditions),
    STRUCT('Sheep' AS card_name, 0 AS conditions),
    STRUCT('Great Hornbill' AS card_name, 0 AS conditions),
    STRUCT('Eurasian Eagle-owl' AS card_name, 1 AS conditions),
    STRUCT('Common Wombat' AS card_name, 0 AS conditions),
    STRUCT('Ring-tailed Lemur' AS card_name, 0 AS conditions),
    STRUCT('Horse Whisperer' AS card_name, 1 AS conditions),
    STRUCT('Expert In Small Animals' AS card_name, 0 AS conditions),
    STRUCT('Sharknose Goby' AS card_name, 0 AS conditions),
    STRUCT('Mediterranean Rainbow Wrasse' AS card_name, 0 AS conditions),
    STRUCT('Sand Tiger Shark' AS card_name, 1 AS conditions),
    STRUCT('White Stork' AS card_name, 1 AS conditions),
    STRUCT('Chinese Water Dragon' AS card_name, 0 AS conditions),
    STRUCT('Expert In Predators' AS card_name, 0 AS conditions),
    STRUCT('Laughing Kookaburra' AS card_name, 1 AS conditions),
    STRUCT('Sea Turtle Tank' AS card_name, 0 AS conditions),
    STRUCT('Primatologist' AS card_name, 0 AS conditions),
    STRUCT('Spotted Hyena Compound' AS card_name, 0 AS conditions),
    STRUCT('Collared Mangabey' AS card_name, 1 AS conditions),
    STRUCT('Coconut Lorikeet' AS card_name, 0 AS conditions),
    STRUCT('Breeding Program' AS card_name, 2 AS conditions),
    STRUCT('Inland Taipan' AS card_name, 2 AS conditions),
    STRUCT('Jaguar' AS card_name, 1 AS conditions),
    STRUCT('Okapi Stable' AS card_name, 0 AS conditions),
    STRUCT('Wolverine' AS card_name, 0 AS conditions),
    STRUCT('Wolf' AS card_name, 0 AS conditions),
    STRUCT('Guinea Pig' AS card_name, 0 AS conditions),
    STRUCT('Malayan Tapir' AS card_name, 0 AS conditions),
    STRUCT('American Whitespotted Filefish' AS card_name, 0 AS conditions),
    STRUCT('Greater Flamingo' AS card_name, 0 AS conditions),
    STRUCT('Herpetologist' AS card_name, 0 AS conditions),
    STRUCT('Dusky-leaf Monkey' AS card_name, 0 AS conditions),
    STRUCT('Stoat' AS card_name, 1 AS conditions),
    STRUCT('Conference On Europe' AS card_name, 0 AS conditions),
    STRUCT('Alpaca' AS card_name, 0 AS conditions),
    STRUCT('Golden Lion Tamarin' AS card_name, 0 AS conditions),
    STRUCT('Northern Cassowary' AS card_name, 1 AS conditions),
    STRUCT('Migration Recording' AS card_name, 1 AS conditions),
    STRUCT('Cougar' AS card_name, 0 AS conditions),
    STRUCT('Sponsorship: Elephants' AS card_name, 1 AS conditions),
    STRUCT('Conference On Australia' AS card_name, 0 AS conditions),
    STRUCT('Common Wall Lizard' AS card_name, 0 AS conditions),
    STRUCT('American Alligator' AS card_name, 0 AS conditions),
    STRUCT('Expert In Herbivores' AS card_name, 0 AS conditions),
    STRUCT('Rhesus Monkey Park' AS card_name, 0 AS conditions),
    STRUCT('Ecuadorian Squirrel Monkey' AS card_name, 0 AS conditions),
    STRUCT('Yellow-throated Marten' AS card_name, 0 AS conditions),
    STRUCT('Reindeer' AS card_name, 0 AS conditions),
    STRUCT('Sponsorship: Vultures' AS card_name, 1 AS conditions),
    STRUCT('Rock Monitor' AS card_name, 0 AS conditions),
    STRUCT('Barn Owl' AS card_name, 0 AS conditions),
    STRUCT('Barred Owl Hut' AS card_name, 0 AS conditions),
    STRUCT('Expert On Australia' AS card_name, 0 AS conditions),
    STRUCT('Marine Biologist' AS card_name, 0 AS conditions),
    STRUCT('Coquerel\'s Sifaka' AS card_name, 0 AS conditions),
    STRUCT('Sponsorship: Lions' AS card_name, 1 AS conditions),
    STRUCT('Greater Rhea' AS card_name, 0 AS conditions),
    STRUCT('European Grass Snake' AS card_name, 0 AS conditions),
    STRUCT('Tambaqui' AS card_name, 0 AS conditions),
    STRUCT('Native Seabirds' AS card_name, 1 AS conditions),
    STRUCT('Waza Special Assignment' AS card_name, 1 AS conditions),
    STRUCT('Sponsorship: Reptiles' AS card_name, 1 AS conditions),
    STRUCT('Breeding Cooperation' AS card_name, 2 AS conditions),
    STRUCT('Short-snouted Seahorse' AS card_name, 0 AS conditions),
    STRUCT('Expert On Europe' AS card_name, 0 AS conditions),
    STRUCT('Release Of Patents' AS card_name, 1 AS conditions),
    STRUCT('Slow Worm' AS card_name, 0 AS conditions),
    STRUCT('Japanese Macaque' AS card_name, 1 AS conditions),
    STRUCT('Common Octopus' AS card_name, 1 AS conditions),
    STRUCT('Red Deer' AS card_name, 0 AS conditions),
    STRUCT('Frilled Lizard' AS card_name, 0 AS conditions),
    STRUCT('Fennec Fox' AS card_name, 0 AS conditions),
    STRUCT('African Ostrich' AS card_name, 0 AS conditions),
    STRUCT('Platypus' AS card_name, 0 AS conditions),
    STRUCT('Llama' AS card_name, 0 AS conditions),
    STRUCT('Expert In Large Animals' AS card_name, 0 AS conditions),
    STRUCT('Australian Dingo' AS card_name, 0 AS conditions),
    STRUCT('Native Lizards' AS card_name, 1 AS conditions),
    STRUCT('Franchise Business' AS card_name, 1 AS conditions),
    STRUCT('Western Green Mamba' AS card_name, 2 AS conditions),
    STRUCT('Crested Porcupine' AS card_name, 0 AS conditions),
    STRUCT('Thorny Devil' AS card_name, 0 AS conditions),
    STRUCT('Cinereous Vulture' AS card_name, 0 AS conditions),
    STRUCT('Cheetah' AS card_name, 0 AS conditions),
    STRUCT('Muskox' AS card_name, 1 AS conditions),
    STRUCT('Bolivian Red Howler' AS card_name, 0 AS conditions),
    STRUCT('Waza Small Animal Program' AS card_name, 1 AS conditions),
    STRUCT('Marine Research Expedition' AS card_name, 0 AS conditions),
    STRUCT('Broad-snouted Caiman' AS card_name, 0 AS conditions),
    STRUCT('European Bison' AS card_name, 1 AS conditions),
    STRUCT('Indian Rock Python' AS card_name, 2 AS conditions),
    STRUCT('European Pond Turtle' AS card_name, 0 AS conditions),
    STRUCT('Sloth Bear' AS card_name, 0 AS conditions),
    STRUCT('(domestic) Goat' AS card_name, 0 AS conditions),
    STRUCT('Common Agama' AS card_name, 0 AS conditions),
    STRUCT('Veiled Chameleon' AS card_name, 0 AS conditions),
    STRUCT('New Zealand Sea Lion' AS card_name, 0 AS conditions),
    STRUCT('Marabou' AS card_name, 0 AS conditions),
    STRUCT('Farm Cat' AS card_name, 1 AS conditions),
    STRUCT('European Badger' AS card_name, 0 AS conditions),
    STRUCT('Green Sea Turtle' AS card_name, 0 AS conditions),
    STRUCT('Northern Giraffe' AS card_name, 0 AS conditions),
    STRUCT('Zooplankton' AS card_name, 0 AS conditions),
    STRUCT('Eurasian Lynx' AS card_name, 2 AS conditions),
    STRUCT('Caracal' AS card_name, 0 AS conditions),
    STRUCT('Mantled Guereza' AS card_name, 0 AS conditions),
    STRUCT('Free-range New World Monkeys' AS card_name, 1 AS conditions),
    STRUCT('African Spurred Tortoise' AS card_name, 0 AS conditions),
    STRUCT('Saltwater Crocodile' AS card_name, 1 AS conditions),
    STRUCT('Common European Adder' AS card_name, 1 AS conditions),
    STRUCT('Gould\'s Monitor' AS card_name, 0 AS conditions),
    STRUCT('Emu' AS card_name, 2 AS conditions)
  ])
),
played_cards_raw AS (
  SELECT
    table_id,
    player,
    pa.animal AS card_name
  FROM `freestyle-190711.ark_nova.game_log_stat_v2`
  CROSS JOIN UNNEST(IFNULL(played_animals, [])) AS pa
  WHERE pa.animal IS NOT NULL

  UNION ALL

  SELECT
    table_id,
    player,
    ps.sponsor AS card_name
  FROM `freestyle-190711.ark_nova.game_log_stat_v2`
  CROSS JOIN UNNEST(IFNULL(played_sponsors, [])) AS ps
  WHERE ps.sponsor IS NOT NULL
),
played_cards AS (
  SELECT DISTINCT
    table_id,
    player,
    card_name
  FROM played_cards_raw
),
game_totals AS (
  SELECT
    p.table_id,
    p.player,
    COUNT(*) AS cards_played,
    SUM(COALESCE(c.conditions, 0)) AS conditions_fulfilled
  FROM played_cards AS p
  LEFT JOIN condition_values AS c USING (card_name)
  GROUP BY p.table_id, p.player
)
SELECT
  table_id,
  player,
  cards_played,
  conditions_fulfilled
FROM game_totals
ORDER BY conditions_fulfilled DESC, table_id, player;
